---
- hosts: all
  become: true
  tasks:

  - name: Install Apache2/httpd on Ubuntu/Fedora
    ansible.builtin.package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
