- name: create user
  tags: always
  ansible.builtin.user:
    name: ayep
    groups: root

- name: add sudoers file for ayep
  tags: always
  ansible.builtin.copy:
    src: sudoer_ayep
    dest: /etc/sudoers.d/ayep
    owner: root
    group: root
    mode: 0440

- name: add ssh key for ayep user
  tags: always
  ansible.builtin.authorized_key:
    user: ayep
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILwtrDKNv6jOrSFDq9kb1eOWqivHI9+6GfjBIh3TquAX ansible"
